### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by rcrooks** [blaqbern/eclectic-syntax#1]
HI @blaqbern just wondering what font that is in the screenshots? Nice one!

**Comment by blaqbern** [comment]
Hi,
Thanks. It's [Source Code Pro](http://www.fontsquirrel.com/fonts/source-code-pro) Extra Light. You may find the Light or even Regular varieties to be a bit more forgiving to the eyes for long sessions. I find I'm leaning that way of late. But because Extra Light looks so classy, it seemed right for the screenshot. :smiley:
